use_frameworks!

platform :ios, '8.0'

target 'ProjectYuri' do
    
  pod 'ZSUtils', '~> 0.0.6'
  pod 'SnapKit', '~> 4.2.0'
  pod 'MJRefresh', '~> 3.2.0'
  pod 'RxSwift', '~> 4.5.0'
  pod 'RxCocoa', '~> 4.5.0'
  pod 'RxDataSources', '~> 3.1.0'
  pod 'Moya/RxSwift', '~> 13.0.1'
  pod 'HandyJSON', '~> 5.0.0'
  pod 'SDWebImage', '~> 5.1.0'
  pod 'SVProgressHUD', '~> 2.2.5'
  pod 'SGPagingView', '~> 1.6.0'
  
end
